apiVersion: v1
kind: Pod
metadata:
  name: myfirstPod
  labels:
    app: web
spec:
  containers:
    - name: hello-world
      image: tutum/hello-world
      ports:
        - containerPort: 80
          protocol: TCP

