apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-custom-nginx
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: myapp
          image: gsalahacr.azurecr.io/gsg-bootcamp-service:v1
          ports:
            - containerPort: 80
          env:
            - name: environment
              valueFrom:
                configMapKeyRef:
                  name: myapp-config-map
                  key: environment
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: myapp-config-map
                  key: log_level