apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-custom-nginx
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: myapp
          image: tutum/hello-world
          ports:
            - containerPort: 80
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mydb-password
                  key: db-password